language: cpp
compiler: gcc

addons:
	apt:
		sources:
			- ubuntu-toolchain-r-test
		packages:
			- gcc-7
			- g++-7

before_script:
	- mkdir build

script:
	- export CC=gcc-7
	- export CXX=g++-7
	- cmake --build ./build