dist: trusty
language: cpp

matrix:
    include:
        - os: linux
          addons:
            apt:
                - ubuntu-toolchain-r-test
                - george-edison55-precise-backports
            packages:
                - g++-7
                - cmake-data
                - cmake
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
    - eval "${MATRIX_EVAL}"
    - mkdir -p build
    - cd build

script:
    - cmake ..
    - make
    - cd ..