language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7

before_script:
    - mkdir -p build
    - cd build

script:
    - cmake ..
    - make
    - cd ..