dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

before_script:
  - mkdir -p build

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - cd build
  - cmake ..
  - make
  - cd ..